<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '少妇白洁',
    'style' => '',
    'thumb' => '',
    'keywords' => '少妇白洁',
    'description' => '少妇白洁',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301825',
    'updatetime' => '1507351584',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '9',
    'typeid' => '0',
    'title' => '少妇白洁',
    'style' => '',
    'thumb' => '',
    'keywords' => '白洁 少妇',
    'description' => '少妇白洁',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=9&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301913',
    'updatetime' => '1507351578',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>