<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '乱伦文学',
    'style' => '',
    'thumb' => '',
    'keywords' => '文学',
    'description' => '乱伦文学',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301938',
    'updatetime' => '1507302285',
    'hitsid' => 'c-1-4',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '10',
    'typeid' => '0',
    'title' => '测试下哦',
    'style' => '',
    'thumb' => 'http://www.test.com/uploadfile/2017/1006/20171006111854939.jpg',
    'keywords' => '测试下哦',
    'description' => 'daddy',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=10&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507556327',
    'updatetime' => '1507556499',
    'hitsid' => 'c-1-5',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
);
?>