<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '10',
    'typeid' => '0',
    'title' => '乱伦文学',
    'style' => '',
    'thumb' => '',
    'keywords' => '文学',
    'description' => '乱伦文学',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=10&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301938',
    'updatetime' => '1510840057',
    'hitsid' => 'c-1-4',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '少妇白洁',
    'style' => '',
    'thumb' => '',
    'keywords' => '少妇白洁',
    'description' => '少妇白洁',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301825',
    'updatetime' => '1511061781',
    'hitsid' => 'c-1-2',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '10',
    'typeid' => '0',
    'title' => '测试下哦',
    'style' => '',
    'thumb' => 'http://www.test.com/uploadfile/2017/1006/20171006111854939.jpg',
    'keywords' => '测试下哦',
    'description' => 'daddy',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=10&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507556327',
    'updatetime' => '1507556499',
    'hitsid' => 'c-1-5',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '9',
    'typeid' => '0',
    'title' => '少妇白洁',
    'style' => '',
    'thumb' => '',
    'keywords' => '白洁 少妇',
    'description' => '少妇白洁',
    'posids' => '0',
    'url' => 'http://www.test.com/index.php?m=content&c=index&a=show&catid=9&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1507301913',
    'updatetime' => '1507351578',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>